import React, { useState } from 'react';
import { Terminal, ShieldCheck, Copy, Check, Download, WrapText } from 'lucide-react';
import { api } from '../services/api';
import CodeCard from './CodeCard';

export default function InvestigationStepper({ steps, sessionId }) {
  const buildConsolidatedText = (stepsList) => {
    if (!stepsList || stepsList.length === 0) return null;
    const valid = stepsList.filter((s) => s.diagnostic_sql && s.diagnostic_sql.trim());
    if (!valid.length) return null;
    const header = [
      "-- ============================================================",
      "-- YONDER GRAPH CONSOLIDATED INCIDENT DIAGNOSTIC SCRIPT",
      "-- Generated by ResolveTriageAgent | Tier 2 AST Read-Only Safe",
      "-- ============================================================",
      "",
    ];
    valid.forEach((s) => {
      const title = s.step_title || `Step ${s.step_number || ''}`;
      header.push(`-- ------------------------------------------------------------`);
      header.push(`-- Step ${s.step_number || 1}: ${title}`);
      header.push(`-- ------------------------------------------------------------`);
      const cleanSql = s.diagnostic_sql.trim().replace(/;+$/, '');
      header.push(`${cleanSql};`);
      header.push("");
    });
    return {
      consolidated_sql: header.join("\n"),
      tier2_valid: true,
      step_count: valid.length,
    };
  };

  const [consolidatedSQL, setConsolidatedSQL] = useState(() => buildConsolidatedText(steps));
  const [isConsolidating, setIsConsolidating] = useState(false);
  const [hasCopiedAll, setHasCopiedAll] = useState(false);
  const [isWordWrap, setIsWordWrap] = useState(false);

  // Update consolidated SQL if steps change
  React.useEffect(() => {
    if (steps && steps.length > 0) {
      setConsolidatedSQL(buildConsolidatedText(steps));
    }
  }, [steps]);

  if (!steps || steps.length === 0) return null;

  const hasAnySQL = steps.some((s) => s.diagnostic_sql && s.diagnostic_sql.trim());

  const handleConsolidateSQL = async () => {
    setIsConsolidating(true);
    try {
      const res = await api.consolidateSQL(steps, sessionId);
      setConsolidatedSQL(res);
    } catch (err) {
      console.error("SQL consolidation failed:", err);
    } finally {
      setIsConsolidating(false);
    }
  };

  const copyConsolidated = () => {
    if (!consolidatedSQL?.consolidated_sql) return;
    navigator.clipboard.writeText(consolidatedSQL.consolidated_sql);
    setHasCopiedAll(true);
    setTimeout(() => setHasCopiedAll(false), 2000);
  };

  const downloadConsolidated = () => {
    if (!consolidatedSQL?.consolidated_sql) return;
    const blob = new Blob([consolidatedSQL.consolidated_sql], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident_diagnostic_${Date.now()}.sql`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="my-3.5 font-mono">
      <div className="text-[10px] uppercase tracking-wider text-blue-600 dark:text-blue-400 font-semibold mb-2.5 flex items-center space-x-1.5">
        <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
        <span>Investigation Steps</span>
      </div>

      <div className="relative pl-6 space-y-4">
        {/* Vertical Dotted Connector Line */}
        <div className="absolute left-2.5 top-3 bottom-3 w-px border-l-2 border-dotted border-blue-400/50 dark:border-blue-500/40 pointer-events-none" />

        {steps.map((step, idx) => (
          <div key={idx} className="relative group">
            {/* Step Number Badge */}
            <div className="absolute -left-6 top-0.5 flex items-center justify-center w-5 h-5 rounded-full bg-blue-50 dark:bg-blue-950/80 border border-blue-500/60 text-blue-600 dark:text-blue-400 font-bold text-[10px] shadow-xs z-10">
              {step.step_number || idx + 1}
            </div>

            {/* Step Card */}
            <div className="p-3.5 bg-white dark:bg-[#121216] border border-zinc-200/80 dark:border-zinc-800 rounded-lg shadow-2xs space-y-2">
              <div className="flex items-center justify-between gap-2">
                <span className="font-semibold text-xs text-zinc-900 dark:text-zinc-100">
                  {step.step_title || `Step ${step.step_number}`}
                </span>
                {step.diagnostic_sql && (
                  <span className="px-1.5 py-0.5 rounded bg-emerald-50 dark:bg-emerald-950/30 text-emerald-600 dark:text-emerald-400 text-[10px] border border-emerald-200/50 dark:border-emerald-900/40 flex items-center space-x-1">
                    <ShieldCheck size={10} />
                    <span>Tier 2 AST Safe</span>
                  </span>
                )}
              </div>

              <p className="text-[11px] text-zinc-600 dark:text-zinc-300 leading-relaxed">
                {step.description}
              </p>

              {/* Per-Step Diagnostic SQL */}
              {step.diagnostic_sql && (
                <div className="pt-1.5">
                  <CodeCard
                    title={`Diagnostic SQL — Step ${step.step_number || idx + 1}`}
                    code={step.diagnostic_sql}
                    language="sql"
                  />
                </div>
              )}

              {/* Expected Outcome */}
              {step.expected_outcome && (
                <div className="text-[10px] bg-zinc-50 dark:bg-[#0e0e11] p-2 rounded border border-zinc-200/60 dark:border-zinc-800/80 text-zinc-500 dark:text-zinc-400">
                  <span className="font-semibold text-zinc-700 dark:text-zinc-300">Expected Outcome: </span>
                  <span>{step.expected_outcome}</span>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Button to Generate SQL Script */}
      {hasAnySQL && (
        <div className="mt-4 pt-3 border-t border-zinc-200/80 dark:border-zinc-800/80">
          {!consolidatedSQL ? (
            <button
              onClick={handleConsolidateSQL}
              disabled={isConsolidating}
              className="w-full flex items-center justify-center py-2 px-3 rounded-lg bg-blue-50/80 hover:bg-blue-100 dark:bg-blue-950/40 dark:hover:bg-blue-900/50 border border-blue-600 dark:border-blue-500 text-blue-700 dark:text-blue-300 text-xs font-semibold shadow-xs transition-colors cursor-pointer disabled:opacity-50"
            >
              <span>{isConsolidating ? 'Consolidating SQL Script...' : 'Generate SQL Script'}</span>
            </button>
          ) : (
            <div className="p-3 bg-zinc-900 dark:bg-[#09090b] border border-blue-900/60 rounded-lg text-white space-y-2">
              <div className="flex items-center justify-between gap-2 flex-wrap">
                <div className="flex items-center space-x-1.5 text-xs text-blue-300 font-semibold truncate">
                  <Terminal size={13} className="text-blue-400 shrink-0" />
                  <span className="truncate">Oracle Diagnostic SQL Script</span>
                </div>

                <div className="flex items-center space-x-1.5 shrink-0">
                  <button
                    onClick={() => setIsWordWrap(!isWordWrap)}
                    className={`p-1 rounded text-[10px] flex items-center space-x-1 px-2 transition-colors cursor-pointer ${isWordWrap
                        ? 'bg-blue-600/40 text-blue-300 border border-blue-500/50 font-bold'
                        : 'bg-zinc-800 hover:bg-zinc-700 text-zinc-300'
                      }`}
                    title={isWordWrap ? "Disable Text Wrap" : "Enable Text Wrap"}
                  >
                    <WrapText size={11} className={isWordWrap ? "text-blue-400" : "text-zinc-400"} />
                    <span>Wrap</span>
                  </button>
                  <button
                    onClick={copyConsolidated}
                    className="p-1 rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-[10px] flex items-center space-x-1 px-2 transition-colors cursor-pointer"
                    title="Copy Script"
                  >
                    {hasCopiedAll ? <Check size={11} className="text-emerald-400" /> : <Copy size={11} />}
                    <span>{hasCopiedAll ? 'Copied' : 'Copy'}</span>
                  </button>
                  <button
                    onClick={downloadConsolidated}
                    className="p-1 rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-[10px] flex items-center space-x-1 px-2 transition-colors cursor-pointer"
                    title="Download .sql"
                  >
                    <Download size={11} />
                    <span>.sql</span>
                  </button>
                </div>
              </div>

              <pre className={`p-2.5 bg-black/60 rounded border border-zinc-800 text-[11px] font-mono text-emerald-400 custom-scrollbar leading-relaxed ${isWordWrap ? 'whitespace-pre-wrap break-words overflow-x-hidden' : 'overflow-x-auto whitespace-pre'}`}>
                {consolidatedSQL.consolidated_sql}
              </pre>

              <div className="flex items-center justify-between text-[10px] text-zinc-400">
                <span className="text-emerald-400 flex items-center space-x-1">
                  <ShieldCheck size={11} />
                  <span>Tier 2 AST Safeguard Verified</span>
                </span>
                <span>{consolidatedSQL.step_count} step queries merged</span>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
