"""
Yonder Graph — Oracle SQL Validator (Tier 2 Deterministic Hard Guard)

Pure Python AST interceptor using sqlparse that operates as an immutable
gatekeeper for all Oracle SQL generated by the agent inference engine.

Enforcements:
  1. Strict read-only: blocks INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE,
     MERGE, GRANT, REVOKE, EXEC, EXECUTE, CREATE, REPLACE, CALL
  2. Oracle syntax verification: validates bind parameters, string concatenation,
     and table aliases
  3. Query bounds injection: appends ROWNUM <= 100 or FETCH FIRST 100 ROWS ONLY
     if no row cap is present
  4. Schema match guard: validates referenced tables against active Neo4j nodes
  5. Parameter sanitization integration
"""

import re
import logging
from typing import Any, Dict, List, Optional, Set, Tuple
from dataclasses import dataclass, field

import sqlparse
from sqlparse.sql import (
    Statement,
    Identifier,
    IdentifierList,
    Where,
    Parenthesis,
    Function,
)
from sqlparse.tokens import Keyword, DML, DDL, Name, Punctuation

from backend.governance.safety_rules import (
    MUTATION_TOKENS,
    STRUCTURAL_DDL_TOKENS,
    ALLOWED_STATEMENT_TYPES,
    DEFAULT_ROW_LIMIT,
    ROWNUM_CLAUSE,
    FETCH_FIRST_CLAUSE,
    RiskLevel,
)
from backend.governance.parameter_sanitizer import (
    ParameterSanitizer,
    BIND_PARAM_EXTRACTOR,
)

logger = logging.getLogger(__name__)


@dataclass
class ValidationResult:
    """Result of SQL validation through the Tier 2 interceptor."""

    is_valid: bool
    validated_sql: str
    original_sql: str
    flags: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    tables_referenced: Set[str] = field(default_factory=set)
    bind_parameters: List[str] = field(default_factory=list)
    row_limit_injected: bool = False
    risk_level: str = RiskLevel.LOW_RISK_READONLY

    def to_dict(self) -> Dict[str, Any]:
        return {
            "is_valid": self.is_valid,
            "validated_sql": self.validated_sql,
            "original_sql": self.original_sql,
            "flags": self.flags,
            "errors": self.errors,
            "warnings": self.warnings,
            "tables_referenced": list(self.tables_referenced),
            "bind_parameters": self.bind_parameters,
            "row_limit_injected": self.row_limit_injected,
            "risk_level": self.risk_level,
        }


class OracleSQLValidator:
    """
    Tier 2 Deterministic Hard Guard — Oracle SQL AST Interceptor.
    
    Operates as a fail-closed gatekeeper: if any check fails, the entire
    query is rejected. No mutation or unvalidated SQL passes through.
    """

    def __init__(self, known_tables: Optional[Set[str]] = None):
        """
        Initialize the validator.
        
        Args:
            known_tables: Set of Oracle table names registered in Neo4j.
                          If None, schema validation is skipped.
        """
        self._known_tables: Optional[Set[str]] = (
            {t.upper() for t in known_tables} if known_tables else None
        )

    def update_known_tables(self, tables: Set[str]) -> None:
        """Update the set of known tables from Neo4j schema."""
        self._known_tables = {t.upper() for t in tables}

    def validate(self, sql: str) -> ValidationResult:
        """
        Run the complete Tier 2 validation pipeline on a SQL string.
        
        Pipeline order:
          1. Parse and normalize
          2. Mutation token scan (hard block)
          3. Statement type verification
          4. Table extraction and schema match
          5. Bind parameter extraction and validation
          6. Row limit injection
          7. Oracle syntax verification
        """
        result = ValidationResult(
            is_valid=True,
            validated_sql=sql.strip(),
            original_sql=sql.strip(),
        )

        if not sql or not sql.strip():
            result.is_valid = False
            result.errors.append("Empty SQL statement")
            return result

        # Normalize whitespace
        normalized = " ".join(sql.strip().split())
        result.validated_sql = normalized

        # Step 1: Parse with sqlparse
        try:
            parsed_statements = sqlparse.parse(normalized)
        except Exception as e:
            result.is_valid = False
            result.errors.append(f"SQL parsing failed: {e}")
            return result

        if not parsed_statements:
            result.is_valid = False
            result.errors.append("No valid SQL statements found")
            return result

        # Only allow single statements (prevent multi-statement injection)
        if len(parsed_statements) > 1:
            result.is_valid = False
            result.errors.append(
                "Multiple SQL statements detected. Only single SELECT "
                "statements are permitted for diagnostic queries."
            )
            result.flags.append("MULTI_STATEMENT_BLOCKED")
            return result

        stmt = parsed_statements[0]

        # Step 2: Mutation token scan (HARD BLOCK)
        mutation_check = self._check_mutation_tokens(stmt, result)
        if not mutation_check:
            return result

        # Step 3: Statement type verification
        self._check_statement_type(stmt, result)
        if not result.is_valid:
            return result

        # Step 4: Table extraction and schema match
        self._extract_and_validate_tables(stmt, result)
        if not result.is_valid:
            return result

        # Step 5: Bind parameter extraction
        result.bind_parameters = ParameterSanitizer.extract_bind_params(
            normalized
        )

        # Step 6: Row limit injection
        self._inject_row_limit(result)

        # Step 7: Oracle syntax verification
        self._verify_oracle_syntax(result)

        return result

    def _check_mutation_tokens(
        self, stmt: Statement, result: ValidationResult
    ) -> bool:
        """
        Scan for mutation tokens. HARD BLOCK on any match.
        
        This is the most critical check — no mutation SQL must ever pass.
        """
        # Flatten all tokens and check against the blocked set
        all_tokens = list(stmt.flatten())

        for token in all_tokens:
            token_upper = token.ttype
            token_value = token.value.upper().strip()

            # Check DML/DDL token types
            if token.ttype in (DML, DDL):
                if token_value in MUTATION_TOKENS:
                    result.is_valid = False
                    result.errors.append(
                        f"BLOCKED: Mutation token '{token.value}' detected. "
                        f"Only read-only SELECT statements are permitted for "
                        f"diagnostic queries. Use MOCA commands or authorized "
                        f"UI workflows for data modifications."
                    )
                    result.flags.append(f"MUTATION_BLOCKED_{token_value}")
                    if token_value in STRUCTURAL_DDL_TOKENS:
                        result.risk_level = RiskLevel.CRITICAL_RISK_STRUCTURAL
                    else:
                        result.risk_level = RiskLevel.HIGH_RISK_MUTATION
                    return False

            # Also check Keyword tokens for mutation commands
            if token.ttype is Keyword or token.ttype in Keyword:
                if token_value in MUTATION_TOKENS:
                    result.is_valid = False
                    result.errors.append(
                        f"BLOCKED: Mutation keyword '{token.value}' detected "
                        f"in query. Diagnostic queries must be read-only."
                    )
                    result.flags.append(f"MUTATION_BLOCKED_{token_value}")
                    result.risk_level = RiskLevel.HIGH_RISK_MUTATION
                    return False

        # Additional regex scan for edge cases sqlparse might miss
        sql_upper = result.validated_sql.upper()
        for token in MUTATION_TOKENS:
            # Match whole-word occurrences not inside string literals
            pattern = r"\b" + re.escape(token) + r"\b"
            if re.search(pattern, sql_upper):
                # Verify it's not inside a string literal
                if not self._is_in_string_literal(
                    result.validated_sql, token
                ):
                    result.is_valid = False
                    result.errors.append(
                        f"BLOCKED: Mutation keyword '{token}' found in SQL. "
                        f"All diagnostic queries must be read-only SELECT."
                    )
                    result.flags.append(f"MUTATION_BLOCKED_{token}")
                    result.risk_level = RiskLevel.HIGH_RISK_MUTATION
                    return False

        return True

    def _is_in_string_literal(self, sql: str, token: str) -> bool:
        """Check if a token occurrence is inside a SQL string literal."""
        in_string = False
        pos = 0
        token_upper = token.upper()
        sql_upper = sql.upper()

        while pos < len(sql):
            if sql[pos] == "'" and (pos == 0 or sql[pos - 1] != "'"):
                in_string = not in_string
            elif not in_string and sql_upper[pos:].startswith(token_upper):
                return False
            pos += 1
        return True

    def _check_statement_type(
        self, stmt: Statement, result: ValidationResult
    ) -> None:
        """Verify the statement begins with an allowed type (SELECT or WITH)."""
        first_token = None
        for token in stmt.tokens:
            if token.ttype in (sqlparse.tokens.Whitespace,
                               sqlparse.tokens.Newline,
                               sqlparse.tokens.Comment.Single,
                               sqlparse.tokens.Comment.Multiline):
                continue
            first_token = token
            break

        if first_token is None:
            result.is_valid = False
            result.errors.append("Could not determine statement type")
            return

        first_value = first_token.value.upper().strip()
        if first_value not in ALLOWED_STATEMENT_TYPES:
            result.is_valid = False
            result.errors.append(
                f"Statement type '{first_value}' is not allowed. "
                f"Only SELECT and WITH (CTE) statements are permitted."
            )
            result.flags.append(f"STATEMENT_TYPE_BLOCKED_{first_value}")

    def _extract_and_validate_tables(
        self, stmt: Statement, result: ValidationResult
    ) -> None:
        """Extract referenced table names and validate against Neo4j schema."""
        tables = set()

        # Extract tables from FROM and JOIN clauses
        sql_upper = result.validated_sql.upper()

        # Pattern: FROM table_name [alias], JOIN table_name [alias]
        from_join_pattern = re.compile(
            r"(?:FROM|JOIN)\s+([A-Za-z_][A-Za-z0-9_]*)",
            re.IGNORECASE,
        )
        matches = from_join_pattern.findall(result.validated_sql)
        for match in matches:
            table_name = match.upper()
            # Skip Oracle keywords that might appear after FROM
            if table_name not in {"DUAL", "SELECT", "WHERE", "ON", "AND",
                                  "OR", "LEFT", "RIGHT", "INNER", "OUTER",
                                  "CROSS", "FULL", "NATURAL"}:
                tables.add(table_name)

        result.tables_referenced = tables

        # Validate against known schema if available
        if self._known_tables is not None and tables:
            unknown_tables = tables - self._known_tables
            if unknown_tables:
                result.is_valid = False
                result.errors.append(
                    f"Unknown table(s) referenced: {', '.join(sorted(unknown_tables))}. "
                    f"All tables must be registered in the Neo4j knowledge graph. "
                    f"Known tables: {', '.join(sorted(self._known_tables))}"
                )
                result.flags.append("UNKNOWN_TABLE_BLOCKED")

    def _inject_row_limit(self, result: ValidationResult) -> None:
        """Inject ROWNUM <= 100 or FETCH FIRST if no row cap is present."""
        sql_upper = result.validated_sql.upper()

        # Check for existing row limits
        has_rownum = "ROWNUM" in sql_upper
        has_fetch_first = "FETCH FIRST" in sql_upper
        has_limit = "LIMIT" in sql_upper  # Not Oracle but defensive
        has_top = re.search(r"\bTOP\s+\d+", sql_upper) is not None

        if has_rownum or has_fetch_first or has_limit or has_top:
            result.warnings.append(
                "Row limit already present in query — no injection needed."
            )
            return

        # Inject ROWNUM <= 100 via wrapping in a subquery
        # This is the safest approach for Oracle SQL
        wrapped = (
            f"SELECT * FROM ({result.validated_sql}) "
            f"WHERE ROWNUM <= {DEFAULT_ROW_LIMIT}"
        )
        result.validated_sql = wrapped
        result.row_limit_injected = True
        result.flags.append("ROW_LIMIT_INJECTED")
        result.warnings.append(
            f"Row limit injected: ROWNUM <= {DEFAULT_ROW_LIMIT}. "
            f"All diagnostic queries are capped to prevent unbounded scans."
        )

    def _verify_oracle_syntax(self, result: ValidationResult) -> None:
        """Verify Oracle-specific syntax patterns."""
        sql = result.validated_sql

        # Verify bind parameters follow Oracle format (:param_name)
        bind_params = BIND_PARAM_EXTRACTOR.findall(sql)
        for param in bind_params:
            if not re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", param):
                result.warnings.append(
                    f"Bind parameter ':{param}' has unusual naming. "
                    f"Expected format: :lowercase_with_underscores"
                )

        # Check for potential SQL injection patterns in non-bind values
        dangerous_patterns = [
            (r"--", "SQL comment (--) detected"),
            (r"/\*", "Block comment (/*) detected"),
            (r";\s*\S", "Multiple statements detected (semicolon followed by content)"),
            (r"UNION\s+ALL\s+SELECT", "UNION ALL SELECT — potential injection vector"),
        ]
        for pattern, message in dangerous_patterns:
            if re.search(pattern, sql, re.IGNORECASE):
                result.warnings.append(
                    f"Suspicious pattern: {message}. Review query carefully."
                )
                result.flags.append("SUSPICIOUS_PATTERN")


def validate_oracle_sql(
    sql: str, known_tables: Optional[Set[str]] = None
) -> ValidationResult:
    """
    Module-level convenience function for Tier 2 SQL validation.
    
    Creates a validator instance and runs the full pipeline.
    """
    validator = OracleSQLValidator(known_tables=known_tables)
    return validator.validate(sql)


def validate_with_neo4j_schema(sql: str) -> ValidationResult:
    """
    Validate SQL against the live Neo4j schema.
    
    Loads current table nodes from Neo4j and validates all referenced
    tables exist in the knowledge graph.
    """
    try:
        from backend.database.neo4j_client import neo4j_client

        table_nodes = neo4j_client.get_table_nodes()
        known = set(table_nodes) if table_nodes else None
    except Exception as e:
        logger.warning(
            "Could not load Neo4j schema for validation: %s. "
            "Proceeding without schema match guard.",
            e,
        )
        known = None

    return validate_oracle_sql(sql, known_tables=known)
